title: gw documentation
description: Documentation for gw
theme: just-the-docs

logo: "/assets/images/gw_icon.png"
favicon_ico: "/assets/images/gw_icon.ico"
color_scheme: dark

baseurl: "/gw"
url: "https://kcleal.github.io"

aux_links: # remove if you don't want this link to appear on your pages
  GitHub Repository: "https://github.com/kcleal/gw"
