name: gw

on:
  push:
  pull_request:

jobs:
  # mingw:
  #   strategy:
  #     fail-fast: false
  #     matrix:
  #       sys: [clang64, ucrt64]
  #   name: ${{ matrix.sys }}
  #   runs-on: windows-latest
  #   defaults:
  #     run:
  #       shell: msys2 {0}
  #   steps:
  #     - uses: actions/checkout@v3
  #     - uses: msys2/setup-msys2@v2
  #       with:
  #         msystem: ${{ matrix.sys }}
  #         update: true
  #         install: make
  #         pacboy: toolchain:p glfw:p skia:p htslib:p freeglut:p glew:p ncurses:p fontconfig:p dlfcn:p libpng:p
  #     - name: build
  #       run: |
  #         make
  #     - name: upload
  #       uses: actions/upload-artifact@v3
  #       with:
  #         name: mingw-${{ matrix.sys }}
  #         path: ${{ github.workspace }}/*.exe

  macos-intel:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          brew install fontconfig glfw htslib icu4c wget zlib node graphicsmagick imagemagick
          npm install --global create-dmg

      - name: build
        run: |
          make prep
          make -j3
        
      - name: package
        run: |
          osacompile -o gw.app deps/gw_applescript_prog.scpt
          mv deps/gw_droplet.icns gw.app/Contents/Resources/droplet.icns
          cp gw gw.app/Contents/MacOS/gw_program
          # ignore code signing error
          create-dmg 'gw.app' --dmg-title='gw-intel.dmg' || true
          mv gw\ undefined.dmg gw-intel.dmg
          
      - name: upload
        uses: actions/upload-artifact@v3
        with:
          name: macos-latest-intel
          path: ${{ github.workspace }}/gw-intel.dmg
