name: gw

on:
  push:
  pull_request:

jobs:
  # mingw:
  #   strategy:
  #     fail-fast: false
  #     matrix:
  #       sys: [clang64, ucrt64]
  #   name: ${{ matrix.sys }}
  #   runs-on: windows-latest
  #   defaults:
  #     run:
  #       shell: msys2 {0}
  #   steps:
  #     - uses: actions/checkout@v3
  #     - uses: msys2/setup-msys2@v2
  #       with:
  #         msystem: ${{ matrix.sys }}
  #         update: true
  #         install: make
  #         pacboy: toolchain:p glfw:p skia:p htslib:p freeglut:p glew:p ncurses:p fontconfig:p dlfcn:p libpng:p
  #     - name: build
  #       run: |
  #         make
  #     - name: upload
  #       uses: actions/upload-artifact@v3
  #       with:
  #         name: mingw-${{ matrix.sys }}
  #         path: ${{ github.workspace }}/*.exe

  macos-intel:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          brew install node graphicsmagick imagemagick
          npm install --global create-dmg
          
      - name: package
        run: |
          make prep
          osacompile -o gw.app deps/gw_applescript_prog.scpt
          cp deps/gw_droplet.icns gw.app/Contents/Resources/droplet.icns
          mkdir -p gw.app/Contents/Frameworks/ && cd gw.app/Contents/Frameworks
          cp -rf ../../../lib .
          cp -rf ../../../include .

          #cp $(brew --Cellar)/curl/8.*/lib/libcurl* ./lib
          #cp -rf $(brew --Cellar)/curl/8.*/include/curl ./include
          
          ls ./lib
          ls ./include
          
          git clone --depth 1 https://github.com/ebiggers/libdeflate.git
          cd libdeflate && CFLAGS+=' -fPIC -O3 ' cmake -B build && CFLAGS+=' -fPIC -O3 ' cmake --build build
          cp build/libdeflate.a ../lib && cp libdeflate.h ../include
          #cp build/libdeflate.a /usr/local/lib && cp libdeflate.h /usr/local/include && cd ../
          echo '----'
          ls ./lib
          ls ./include
          
          wget -O htslib.tar.bz2 https://github.com/samtools/htslib/releases/download/1.17/htslib-1.17.tar.bz2
          tar -xvf htslib.tar.bz2
          mv htslib-1.17 htslib && rm htslib.tar.bz2 && cd htslib
          #./configure --enable-libcurl --enable-s3 --enable-lzma --enable-bz2 --with-libdeflate
          LDFLAGS+='-L../lib ' CPPFLAGS+='-I../include ' ./configure --disable-libcurl --enable-s3 --enable-lzma --enable-bz2 --with-libdeflate
          make -j3
          cp -rf htslib ../include && cp libhts.a ../lib && cd ../
          
          wget https://github.com/glfw/glfw/releases/download/3.3.8/glfw-3.3.8.bin.MACOS.zip
          unzip glfw-3.3.8.bin.MACOS.zip
          cp -rf glfw-3.3.8.bin.MACOS/include/* include
          cp glfw-3.3.8.bin.MACOS/lib-x86_64/libglfw3.a lib
          cp glfw-3.3.8.bin.MACOS/lib-x86_64/libglfw3.a lib/libglfw.a
          
          cp /usr/local/opt/fontconfig/lib/libfontconfig.a ./lib
          
          cp -rf ./lib/skia/third_party/externals/freetype/include/* ./include
          cd ../../../
          pwd
          ls
          echo "--"
          ls include
          echo "--"
          ls lib
          echo "--"
          CONDA_PREFIX="gw.app/Contents/Frameworks" make -j3
          echo "BUILT GW"
          cp gw gw.app/Contents/MacOS/gw_program
          
          #osacompile -o gw.app deps/gw_applescript_prog.scpt
          #cp deps/gw_droplet.icns gw.app/Contents/Resources/droplet.icns
          #cp gw gw.app/Contents/MacOS/gw_program
          echo "CODE SIGNING"
          codesign --remove-signature ./gw.app
          codesign --force --deep -s - gw.app -v
          codesign --verify -vvvv gw.app
          create-dmg 'gw.app' || true
          ls
          mv gw\ undefined.dmg gw-macos-intel.dmg
          
      - name: upload
        uses: actions/upload-artifact@v3
        with:
          name: gw-macos-intel
          path: ${{ github.workspace }}/gw-macos-intel.dmg
          
